- name: Create EC2 Instance
  hosts: localhost
  tasks:
    - ec2:
        key_name: ansible-key
        instance_type:t2.small
        image:ami-0f40cd8c027cef9cb
        wait: yes
        group: ansible
        count: "{{ count }}"
        vpc_subnet_id: subnet-0c212b425f8ada0aa
        assign_public_ip: yes
        region: us-east-1
      register: out
   
    - debug:
        msg: "{{out}}"
    - add_host:
        hostname: "{{item.public_ip}}"
        groupname: myservers
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /aws/ansible-key.pem
        ansible_python_interpreter: /usr/bin/python3
      with_items: "{{out.instances}}"

    - wait_for:
        host: "{{ item.public_ip }}"
        port: 3389
        delay: 30 
        timeout: 320
        state: started
      with_items: "{{ out.instances }}"

    - copy:
        content: "{% for host in groups.myservers %}{{ hostvars[host].inventory_hostname }}\n{% endfor %}"
        dest: /tmp/uinventory
      delegate_to: localhost

- name: setup user
  hosts: myservers
  become: yes
  tasks:
    - name: install git & python
      package:
        name: "{{ item }}"
        state: present
      with_items:
          - git
#          - python
    - name: clone git repo
      shell: git clone https://github.com/kotireddy680/windowsinstance.git
      args:
        chdir: /tmp
    - name: create user
      shell: chmod -R 755 /tmp/tse/* ; /tmp/it/userdata.sh
      register: outt
    - debug:
        var: outt
#    - name: remove git
#      command: apt remove -y git
